### ISSUE TITLE
Getting "undefined reference to `__stack_chk_fail'" when building on Linux

### ISSUE THREAD

**Issue by micahswitzer** [Kfeavel/Panix#28]
When building on Linux without a cross-compiler I get these errors:
```
ld: src/drivers/keyboard/keyboard.o: in function `drivers::Keyboard::callback(registers_t)':
/home/micah/src/Panix/src/drivers/keyboard/keyboard.cpp:89: undefined reference to `__stack_chk_fail'
ld: src/cpu/timer/timer.o: in function `cpu::Timer::printTick()':
/home/micah/src/Panix/src/cpu/timer/timer.cpp:42: undefined reference to `__stack_chk_fail'
make: *** [Makefile:37: src/kernel/kernel.bin] Error 1
```
It appears that libssp isn't getting linked when building. See [this StackOverflow post](https://stackoverflow.com/questions/4492799/undefined-reference-to-stack-chk-fail) for a potential solution.

**Comment by Kfeavel** [comment]
We're currently working on porting everything to the 'Switch-To-Grub' branch, so look there for the most recent updates. This branch will be moved to master soon.

**Comment by Kfeavel** [comment]
Merged.
