### ISSUE TITLE
Concept of a "Process" Class

### ISSUE THREAD

**Issue by Kfeavel** [Kfeavel/Panix#62]
One of the solutions to some of our process issues might be to create a process class that simple has an initialize function that's called when the process begins and then from there the process object can take care of itself. A concept that's similar to this that has already been implemented into panix are the interrupt handlers. Just a thought, but we need something to make the process of launching a new process easier.

**Comment by micahswitzer** [comment]
So in other words, we need a `ProcessManager` class, or something like it?
