### ISSUE TITLE
Create enum for Driver identification

### ISSUE THREAD

**Issue by Kfeavel** [Kfeavel/Panix#67]
An enum could contain a bunch of information like tag, version, etc. that identifies the driver (maybe a uuid) so that we aren't just relying on strings.

**Comment by Kfeavel** [comment]
@micahswitzer What information should we include in this that would be useful besides a tag? When we request a driver would we have to know all of the information? How should we go about this? (It would be easy enough to implement)

**Comment by micahswitzer** [comment]
Well it depends on why the drivers need to be looked up. If we need to get a specific driver, then all we need is a unique tag, otherwise a driver info struct/class could be added to allow the driver manager to find a driver that matches the requested parameters.
