### ISSUE TITLE
Need a place to set a global driver manager variable

### ISSUE THREAD

**Issue by Kfeavel** [Kfeavel/Panix#69]
Every time I try to do this so that I can access drivers from places like panic() I run into a circular dependency issue. Maybe I need to rethink how panic() works since most other kernels seem to have it in the kernel file itself. If so, how would we call it from other places without importing the kernel header and getting circular dependency there? (Or would we?)

**Comment by micahswitzer** [comment]
Separating out the panic function into a different header sounds fine. We need to discuss exactly what the panic function needs and organize the dependencies accordingly.
